### ISSUE TITLE
Manual instructions in readme are incorrect

### ISSUE THREAD

**Issue by corvino** [pebble/pebble-ios-sdk#23]
The instructions in 'Integrating PebbleKit Manually' don't work.

PebbleKit is a dynamic framework, but adding it to the project doesn't add it to embedded frameworks.

Also, -ObjC shouldn't be needed with dynamic frameworks.

There is no mention of including the PebbleKit-Static framework manually.

**Comment by drodriguez** [comment]
We are trying to release a new version soon. The instructions will be fixed for the dynamic framework (as good as we can).

We still have the line about `-ObjC` for the dynamic framework. We are not sure if it is needed or not. We will try to check the behaviour without it. Notice that the Xcode embedded frameworks link will not be enough for the App Store submission, since the framework is both iOS and Simulator, and you need to strip the final framework from the unwanted architectures.

Here there are as reference, just in case you want to review them earlier. Tell us if you think we should remove some part.

---

## Integrating PebbleKit Using CocoaPods
- Install [CocoaPods](http://www.cocoapods.org) or make sure it is up to date
- Add a Podfile to your project if you don't have one already (Hint: use `pod init`).
- Add this line to the Podfile: `pod 'PebbleKit'`
- Run `pod install`

## Integrating PebbleKit Using Carthage
- Install [Carthage](https://github.com/Carthage/Carthage/releases) or make sure it is up to date
- Add Cartfile to your project if you don't have one already.
- Add this line to the Cartfile: `github "pebble/pebble-ios-sdk"`
- Run `carthage bootstrap`
- Drag `PebbleKit.framework` into your project

## Integrating PebbleKit Manually
- Copy `PebbleKit.framework` somewhere in your project folder.
- On your application target “General” settings tab, in the “Linked Frameworks and Libraries” section, drag and drop `PebbleKit.framework`.
- Also link `ExternalAccessory.framework` and `CoreBluetooth.framework`.
- Add `-ObjC` linker flag to your project's build settings.

Additionally, since `PebbleKit.framework` is compiled for both the device and the simulator, when you upload your app to iTunes Connect, it might be rejected. To avoid this, you need to strip the simulator architectures from the binary before submitting. You can do this in many ways, but we will recommend using Carthage for simplicity:
- Install [Carthage](https://github.com/Carthage/Carthage/releases) or make sure it is up to date
- On your application target “Build Phases” settings tab, click the “+” icon and choose “New Run Script Phase”. Create a Run Script with the following contents:
  
  ``` sh
  /usr/local/bin/carthage copy-frameworks
  ```
  
  and add the paths to the framework under “Input Files”, e.g.:
  
  ```
  $(SRCROOT)/path/to/PebbleKit.framework
  ```

## Integrating with PebbleKit-Static

PebbleKit-Static provides compatibility with iOS 7. We recommend you using PebbleKit, but if you need to provide versions of your app for older iOS version, you can still use this.

You can use PebbleKit-Static either using Cocoapods or manually. Carthage only supports dynamic frameworks, so PebbleKit-Static is not available for Carthage.

Additionally, in every point of the documentation that uses `#import <PebbleKit/PebbleKit.h>` you should use instead `#import <PebbleKit-Static/PebbleKit.h>`.

### Using CocoaPods
- Install [CocoaPods](http://www.cocoapods.org) or make sure it is up to date.
- Add a Podfile to your project if you don’t have one already (Hint: use `pod init`).
- Add this line to the Podfile: `pod 'PebbleKit-Static'`
- Run `pod install`

### Manually
- Copy `PebbleKit-Static.framework` somewhere in your project folder.
- On your application target “General” settings tab, in the “Linked Frameworks and Libraries” section, drag and drop `PebbleKit-Static.framework`.
- Also link `ExternalAccessory.framework` and `CoreBluetooth.framework`.
- Add `-ObjC` linker flag to your project's build settings.
