### ISSUE TITLE
com.apple.private.externalaccessory.showallaccessories

### ISSUE THREAD

**Issue by szysz3** [pebble/pebble-ios-sdk#25]
Hi!

There's a problem with entitlement on iOS 10.0+

`2016-10-29 16:45:49.063492 PebbleKitExample[513:57904] Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement`

I've added following entries to plist:

`<key>UIBackgroundModes</key>
    <array>
        <string>external-accessory</string>
        <string>bluetooth-peripheral</string>
        <string>bluetooth-central</string>
    </array>`

as well as

`<key>NSBluetoothPeripheralUsageDescription</key>
    <string>BT</string>`

and 

`<key>UISupportedExternalAccessoryProtocols</key>
    <array>
        <string>com.getpebble.public</string>
    </array>`

There's no such problem on iOS < 10.0

**Comment by mrcljx** [comment]
Hey @szysz3,

someone had the same issue over at the Apple forums:

https://forums.developer.apple.com/thread/61646

> Thanks, that did the trick - for example: com.getpebble.public protocol string would produce the entitlement error, but changing it to com.GetPebble.com has cleared it up.

Can you check whether their solution solves the issue for you too?

**Comment by shagedorn** [comment]
We saw the same warning, but changing the `UISupportedExternalAccessoryProtocols` to the uppercase version did not resolve the issue.

Instead, we updated the Pebble version (from 2.x to 3.1.0) and the warning is gone. We have yet to test if it works as expected.

**Comment by edwinfinch** [comment]
Anyone know how to actually fix this?

It's my belief that it's iOS 10 being verbose about its logging, regardless, trying to fix this particular log with all solutions I've seen has not worked. 

Changing it to com.GetPebble.com or com.GetPebble.public just causes another error saying that Pebble is missing the UISupportedExternalAccessoryProtocols entitlement.

**Comment by drodriguez** [comment]
I think they changed something in SDK 10, which is why it doesn’t happen when compiling with SDK 9, and it is not checked in iOS 9.

The example app doesn’t have any provisioning profile associated. My theory is that by default, it uses the “asterisk” personal provisioning profile, and the associated entitlements do not have `com.apple.private.externalaccessory.showallaccessories` enabled. But I don’t see how to enable it at all. The only ones related (maybe) we have enabled is `com.apple.external-accessory.wireless-configuration`. This profile was generated October 10th.

Sometimes Apple changes the way the profiles are generated, so for anyone seeing the warning, it might be good to do a simple change and undo the change, and try again. If you are trying with the example app from the pod, you might want to create a provisioning profile for it and enable external accessory usage, and change the application ID to something yours.

We will try to include the new keys for SDK 10 in the example in a future release, for now, the example should be considered compatible only with SDK 9 (which was the current one at the time the last PebbleKit was released).

I can confirm that `com.getpebble.public` is the protocol and it is all in lower case in the firmware, no need to change the casing.

I haven’t been able to confirm any of this, if someone goes through the motions and answers here, I’m sure the community will appreciate it.

**Comment by drodriguez** [comment]
PebbleKit 4.0.0 removes the usage of `ExternalAccessory.framework` and Bluetooth Classic, so this error should not appear anymore.

**Comment by GFilosofi** [comment]
Hi,
Here is my experience. On Xcode 8.1 I can successfully build an old NIB-based Apple project (EADemo) and run it on iOS 10.1.1 device. It works fine with my Bluetooth accessory. Now I have renamed the project and completed the porting to a Storyboard-based project. Running the app on the same iPhone the EA Session crashes and I get the console error
 
_2016-11-29 17:04:00.804421 K5Demo[430:69578] Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement
2016-11-29 17:04:04.736780 K5Demo[430:69578] ERROR - opening session failed as protocol (null) is not declared in Info.plist_
 
For the two cases the Info.plist file is the same, with the "Supported external accessory protocols" string exactly matching the same one exposed by the accessory.

**Comment by drodriguez** [comment]
As I recommend in the previous comment, you should update to PebbleKit 4.0.0, which by removing the need of `ExternalAccessory.framework` removes all the need for declaring supported external accessory protocols and all that stuff related to BT classic.

I don’t know which steps involve your “renaming”, but maybe you are missing some steps. EADemo declared two protocols, none of them will be valid for Pebble. We look into `Info.plist` and look for `com.getpebble.public`, if it is not there, we pass `nil` to the Apple code, which will output the second line you copied there.

As I said before, I think the first line happen with profiles generated before some date, which doesn’t declare the External Accesory background mode. If you create a new one, it will probably go away.

But again, please update to PebbleKit 4.0.0 and all this problems go away.
