### ISSUE TITLE
appMessagesKill does not kill app when called during willTerminate

### ISSUE THREAD

**Issue by jeradesign** [pebble/pebble-ios-sdk#7]
In my app WristVision, I have a UIApplicationWillTerminateNotification notification handler to terminated the watch app when the iPhone app exits. The hander eventually calls:

[self.targetWatch appMessagesKill:^(PBWatch *watch, NSError *error) {...}];

however, the watchapp never exits, and the callback is never called.

This code worked (and continues to work) fine with versions of the iOS SDK prior to 3.0.

**Comment by mrcljx** [comment]
Does that change when you use `UIApplicationDidEnterBackgroundNotification` instead?

Trying to do communication in `UIApplicationWillTerminateNotification` is likely to fail (may it be Bluetooth or web requests). Especially since BLE won't work when you go into background and don't have the `UIBackgroundModes` set accordingly.
